version: '3.3'

services:
  satuankerja:
    build:
      context: ./service-golang
    command: "satuankerja"
    networks:
      - satuankerja
    ports:
      - 8301:8301
    environment:
      SECRET_KEY: 'example'
      POSTGRESQL_HOST: example
      POSTGRESQL_PORT: example
      POSTGRESQL_USER: "example"
      POSTGRESQL_PASSWORD: "example"
      POSTGRESQL_DB_MASTER: "example"

  jabatan:
    build:
      context: ./service-golang
    command: "jabatan"
    networks:
      - jabatan
    ports:
      - 8302:8302
    environment:
      SECRET_KEY: 'example'
      POSTGRESQL_HOST: example
      POSTGRESQL_PORT: example
      POSTGRESQL_USER: "example"
      POSTGRESQL_PASSWORD: "example"
      POSTGRESQL_DB_MASTER: "example"

networks:
  satuankerja:
    external:
      name: gateway

  jabatan:
    external:
      name: gateway
