version: '3.3'

services:
  authserver:
    build:
      context: ./service-python/authserver
    networks:
      - authserver
    environment:
      SECRET_KEY: 'example'
      TOKEN_KEY: 'example'
      POSTGRESQL_HOST: example
      POSTGRESQL_PORT: example

networks:
  authserver:
    external:
      name: gateway
