version: '3.3'

services:
  apigateway:
    build:
      context: ./service-nodejs
    command: npm start
    volumes:
      - ./service-nodejs/apiGateway:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - apigateway
    environment:
      API_GATEWAY_PORT: 80
      SENTRY_DSN: "example"
      REDIS_HOST: example
      REDIS_PORT: example
      DB_MONGO_HOST: example
      DB_MONGO_PORT: example
      MONGO_DB_FILEPATH: "example"
      MONGO_DB_LOGBOOK: "example"
      SECRET_KEY: 'example'
      AUTHENTICATION_PY_SERVICE_URI: "http://authserver"
      MOCKSERVER_NODEJS_SERVICE_URI: "http://mockserver:3000"
      SATUANKERJA_GO_SERVICE_URI: "http://satuankerja:8301"
      JABATAN_GO_SERVICE_URI: "http://jabatan:8302"
      FILEUPLOAD_NODEJS_SERVICE_URI: "http://uploadfile:8201"
      LOGBOOK_NODEJS_SERVICE_URI: "http://logbook:8202"

  mockserver:
    build:
      context: ./service-nodejs
    command: npm start
    volumes:
      - ./service-nodejs/mockserver:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - mockserver

  uploadfile:
    build:
      context: ./service-nodejs
    command: npm start
    volumes:
      - ./service-nodejs/UploadFile:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - uploadfile
    environment:
      DB_MONGO_HOST: example
      DB_MONGO_PORT: example
      MONGO_DB_LOGBOOK: "example"
      SECRET_KEY: 'example'
      AWS_S3_ACCESS_KEY: "example"
      AWS_S3_SECRET_ACCESS_KEY: "example"
      AWS_S3_BUCKET: "example"

  logbook:
    build:
      context: ./service-nodejs
    command: npm start
    volumes:
      - ./service-nodejs/apiLogbook:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - logbook
    environment:
      DB_MONGO_HOST: example
      DB_MONGO_PORT: example
      MONGO_DB_LOGBOOK: "example"
      SECRET_KEY: 'example'

networks:
  apigateway:
    external:
      name: gateway

  mockserver:
    external:
      name: gateway

  uploadfile:
    external:
      name: gateway

  logbook:
    external:
      name: gateway
