version: '3.3'

services:
  authserver:
    build:
      context: ./service-python/authserver
    networks:
      - authserver
    ports:
      - 8081:80
    environment:
      SECRET_KEY: 'cobaaja'
      TOKEN_KEY: 'iyalagidicoba'
      POSTGRESQL_HOST: postgres
      POSTGRESQL_PORT: 5432

networks:
  authserver:
    external:
      name: gateway
