version: '3.3'

services:
  apigateway:
    build:
      context: ./service-nodejs
    command: npm start
    volumes:
      - ./service-nodejs/apiGateway:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - apigateway
    ports:
      - 8080:8080
    environment:
      API_GATEWAY_PORT: 8080
      SENTRY_DSN: "https://9e6969ce6e2e4983822bb4d628e47a35@sentry.io/1784511"
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SECRET_KEY: 'cobaaja'
      AUTHENTICATION_PY_SERVICE_URI: "http://authserver"
      MOCKSERVER_NODEJS_SERVICE_URI: "http://mockserver:3000"
      SATUANKERJA_GO_SERVICE_URI: "http://satuankerja:8301"
      JABATAN_GO_SERVICE_URI: "http://jabatan:8302"
      FILEUPLOAD_NODEJS_SERVICE_URI: "http://uploadfile:8201"
      LOGBOOK_NODEJS_SERVICE_URI: "http://uploadfile:8202"

  mockserver:
    build:
      context: ./service-nodejs
    command: npm start
    volumes:
      - ./service-nodejs/mockserver:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - mockserver

  uploadfile:
    build:
      context: ./service-nodejs
    command: npm start
    volumes:
      - ./service-nodejs/UploadFile:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - uploadfile

  logbook:
    build:
      context: ./service-nodejs
    command: npm start
    volumes:
      - ./service-nodejs/apiLogbook:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - logbook

networks:
  apigateway:
    external:
      name: gateway

  mockserver:
    external:
      name: gateway

  uploadfile:
    external:
      name: gateway

  logbook:
    external:
      name: gateway
