version: '3.3'

services:
  authserver:
    build:
      context: ./service-python/authserver
    networks:
      - authserver
    ports:
      - 80:8081
    env_file: 
      - .env-python

networks:
  authserver:
    external:
      name: gateway
