[[constraint]]
  name = "github.com/gorilla/handlers"
  version = "1.3.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.2"

[[constraint]]
  name = "github.com/joho/godotenv"
  version = "1.3.0"

[[constraint]]
  name = "github.com/auth0/go-jwt-middleware"
  version = "0.0.0"

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.2.0"

[[constraint]]
  name = "github.com/jinzhu/gorm"
  version = "1.9.12"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.2.0"

[prune]
  go-tests = true
  unused-packages = true
